// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN855FEx_SOYc78Uazhp4lZohzcldQcJk',
    appId: '1:718841081927:web:60637e39502286269d8162',
    messagingSenderId: '718841081927',
    projectId: 'mobile2-da34e',
    authDomain: 'mobile2-da34e.firebaseapp.com',
    storageBucket: 'mobile2-da34e.firebasestorage.app',
    measurementId: 'G-LMN0MPJWDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3MHuh7GppyKUX6cFE1TNCt8DkJmZPPro',
    appId: '1:718841081927:android:958acf6c7be8b1909d8162',
    messagingSenderId: '718841081927',
    projectId: 'mobile2-da34e',
    storageBucket: 'mobile2-da34e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjLFjzYycsC-QyY-J4yyfZgQI3SUIaqPA',
    appId: '1:718841081927:ios:559eb34f94b2740a9d8162',
    messagingSenderId: '718841081927',
    projectId: 'mobile2-da34e',
    storageBucket: 'mobile2-da34e.firebasestorage.app',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjLFjzYycsC-QyY-J4yyfZgQI3SUIaqPA',
    appId: '1:718841081927:ios:559eb34f94b2740a9d8162',
    messagingSenderId: '718841081927',
    projectId: 'mobile2-da34e',
    storageBucket: 'mobile2-da34e.firebasestorage.app',
    iosBundleId: 'com.example.projectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN855FEx_SOYc78Uazhp4lZohzcldQcJk',
    appId: '1:718841081927:web:08cf499c89c985499d8162',
    messagingSenderId: '718841081927',
    projectId: 'mobile2-da34e',
    authDomain: 'mobile2-da34e.firebaseapp.com',
    storageBucket: 'mobile2-da34e.firebasestorage.app',
    measurementId: 'G-K5DWSZNTP3',
  );
}
